import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import HomeComponent from "../components/landingPage/Home";
import Player from "../components/Player";
import Loader from "../components/Loader";
export default function Home() {
  const router = useRouter();
  const { status, data: session } = useSession({
    required: true,
    onUnauthenticated() {
      router.replace("/signin");
    },
  });

  // useEffect(() => {
  //   if (session?.error === "RefreshAccessTokenError") {
  //     router.push("/signin"); // Force sign in to hopefully resolve error
  //   }
  // }, [session, router]);
  if (status === "loading") {
    return <Loader />;
  }

  return (
    <div>
      <Head>
        <title>Spotify Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen">
        <Sidebar />
        <div className="bg-gray-900 flex-grow">
          <Navbar />
          <HomeComponent />
        </div>
        <Player />
      </div>
    </div>
  );
}
